"use client";
import { useState } from "react";
import type { ModuleConfig } from "../lib/data";
import { AppIcon } from "./Icon";
export function ModuleView({module,notify}:{module:ModuleConfig;notify:(m:string)=>void}){
 const [modal,setModal]=useState(false); const [query,setQuery]=useState(""); const [view,setView]=useState<"table"|"cards">("table");
 const rows=module.rows.filter(r=>r.some(cell=>typeof cell==="string"&&cell.toLowerCase().includes(query.toLowerCase())));
 function submit(e:React.FormEvent){e.preventDefault();setModal(false);notify(`${module.title.slice(0,-1) || module.title} saved successfully`)}
 return <>
  <div className="module-head"><div><button className="breadcrumb">Workspace</button><span>›</span><span>{module.title}</span><h1>{module.title}</h1><p>{module.subtitle}</p></div><button className="btn primary" onClick={()=>setModal(true)}>＋ {module.action}</button></div>
  <section className="module-stats">{module.stats.map((s,i)=><article key={s.label}><div><span className={`mini-icon ${s.tone||["blue","green","purple","amber"][i]}`}><AppIcon name={module.icon}/></span><small>{s.label}</small></div><strong>{s.value}</strong><p className={s.tone||""}>{s.note}</p></article>)}</section>
  <section className="data-card">
   <div className="data-tools"><div className="table-search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${module.title.toLowerCase()}...`} aria-label={`Search ${module.title}`}/></div><div className="filter-row">{module.filters.map(f=><button key={f}>{f} <span>⌄</span></button>)}<button className="filter-btn">≡ Filters</button></div><div className="view-toggle"><button className={view==="table"?"active":""} onClick={()=>setView("table")}>☷</button><button className={view==="cards"?"active":""} onClick={()=>setView("cards")}>▦</button></div></div>
   {view==="table"?<div className="table-wrap"><table><thead><tr><th><input type="checkbox" aria-label="Select all"/></th>{module.columns.map(c=><th key={c}>{c}</th>)}<th></th></tr></thead><tbody>{rows.map((row,i)=><tr key={i}><td><input type="checkbox" aria-label={`Select row ${i+1}`}/></td>{row.map((cell,j)=><td key={j}>{j===0?<div className="primary-cell"><span className={`record-avatar av-${i%4}`}>{typeof cell==="string"?cell[0]:"B"}</span><strong>{typeof cell==="string"?cell:cell.label}</strong></div>:typeof cell==="string"?(j===4&&cell.includes("%")?<div className="inline-progress"><span>{cell}</span><i><b style={{width:cell}}/></i></div>:cell):<span className={`status ${cell.tone}`}>{cell.label}</span>}</td>)}<td><button className="more" onClick={()=>notify("More actions opened")}>•••</button></td></tr>)}</tbody></table></div>:<div className="record-cards">{rows.map((row,i)=><article key={i}><div className="record-top"><span className={`record-avatar av-${i%4}`}>{String(typeof row[0]==="string"?row[0]:row[0].label)[0]}</span><button>•••</button></div><h3>{typeof row[0]==="string"?row[0]:row[0].label}</h3>{module.columns.slice(1).map((c,j)=><p key={c}><span>{c}</span><b>{typeof row[j+1]==="string"?row[j+1]:(row[j+1] as {label:string}).label}</b></p>)}</article>)}</div>}
   <div className="table-foot"><span>Showing {rows.length} of {Math.max(module.rows.length,24)} results</span><div><button disabled>‹</button><button className="active">1</button><button>2</button><button>3</button><button>›</button></div></div>
  </section>
  {modal&&<div className="modal-backdrop"><button className="modal-dismiss" onClick={()=>setModal(false)} aria-label="Close form"/><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-head"><div><h2 id="modal-title">{module.action}</h2><p>Add the details below. You can edit them later.</p></div><button onClick={()=>setModal(false)} aria-label="Close">×</button></div><form onSubmit={submit}><div className="form-grid">{module.form.map((f,i)=><label key={f.label} className={i===0||i===module.form.length-1?"wide":""}><span>{f.label}</span>{f.type==="select"?<select required><option value="">Select an option</option><option>Skyline Residences</option><option>Metro Plaza Tower</option><option>Riverside Villas</option></select>:f.type==="file"?<div className="file-drop"><b>＋</b><span>Choose files or drag them here</span></div>:<input required={i<4} type={f.type||"text"} placeholder={f.placeholder}/>}</label>)}</div><div className="form-actions"><button type="button" className="btn secondary" onClick={()=>setModal(false)}>Cancel</button><button className="btn primary" type="submit">Save {module.title.toLowerCase().replace(/s$/,"")}</button></div></form></section></div>}
 </>
}
